[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"
  CI = "false"
  GENERATE_SOURCEMAP = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  REACT_APP_SUPABASE_URL = "https://rpgbyockvpannrupicno.supabase.co"
  # REACT_APP_SUPABASE_ANON_KEY is set in Netlify environment variables
  REACT_APP_STRIPE_PUBLISHABLE_KEY = "pk_live_51RGKMXIeHKQHUuvsWtHRFadkGZLUlyyCimVuPbSTySqygdvLL0QSnWZ9R36PZ7KRE7O03JxwZ29MzKvMNSpbHYft00wXKkUqUa"
