[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"
  CI = "false"
  GENERATE_SOURCEMAP = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  REACT_APP_SUPABASE_URL = "https://rpgbyockvpannrupicno.supabase.co"
  REACT_APP_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwZ2J5b2NrdnBhbm5ydXBpY25vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzOTM1MTksImV4cCI6MjA3MTk2OTUxOX0._zvzPGXEkQLh-_IcmS7JcgndKbOq6eD3SViizKH0oos"
  REACT_APP_STRIPE_PUBLISHABLE_KEY = "pk_live_51RGKMXIeHKQHUuvsWtHRFadkGZLUlyyCimVuPbSTySqygdvLL0QSnWZ9R36PZ7KRE7O03JxwZ29MzKvMNSpbHYft00wXKkUqUa"
